codecov:
  require_ci_to_pass: true

flag_management:
  default_rules:
    carryforward: true

coverage:
  status:
    project:
      default:
        flags: [backend]
        target: 85%
        threshold: 1%
      frontend:
        flags: [frontend]
        target: auto
        threshold: 1%
    patch:
      default:
        flags: [backend]
        target: 90%
      frontend:
        flags: [frontend]
        informational: true

fixes:
  - "expenses/::server/"

ignore:
  - "**/internal/wire/**"
  - "**/internal/database/migrations/**"
  - "**/pkg/database/manager/**"
  - "**/internal/mock/**"
  - "**/internal/server/**"
  - "**/pkg/logger/**"
