import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/lib/provider/ThemeProvider";
import { UserProvider } from "@/lib/provider/UserProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>{children}</UserProvider>
          <Toaster
            position="top-right"
            richColors
            theme="dark"
            toastOptions={{
              classNames: {
                toast:
                  "shadow-lg rounded-lg flex items-center p-4 text-xs gap-1.5",
                error: "[&>button]:!bg-red-300",
                info: "[&>button]:!bg-blue-300",
                success: "[&>button]:!bg-green-300",
                warning: "[&>button]:!bg-yellow-300",
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
