import { ThemeHydrationFix } from "@/components/custom/common/ThemeHydrationFix";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that sets up global theming, fonts, and toast notifications for the application.
 *
 * Wraps all pages with theme management, applies Geist fonts, and provides a consistent toast notification system.
 *
 * @param children - The content to render within the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeHydrationFix>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster
              position="top-right"
              richColors
              theme="dark"
              toastOptions={{
                classNames: {
                  toast:
                    "shadow-lg rounded-lg flex items-center p-4 text-xs gap-1.5",
                  error: "[&>button]:!bg-red-300",
                  info: "[&>button]:!bg-blue-300",
                  success: "[&>button]:!bg-green-300",
                  warning: "[&>button]:!bg-yellow-300",
                },
              }}
            />
          </ThemeProvider>
        </ThemeHydrationFix>
      </body>
    </html>
  );
}
