codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 90%

ignore:
  - internal/wire/**
  - internal/database/migration/**
  - internal/database/postgres/**
  - internal/mock/**
  - internal/server/**
  - pkg/logger/**
