name: Format

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Check formatting
        run: |
          test -z "$(gofmt -l .)"
          test -z "$(go vet ./...)"
