name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server 
    env:
      GO111MODULE: on
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go get -d
      - name: Run gosec
        uses: securego/gosec@2
        with:
          args: ./...
