name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Download dependencies
        working-directory: ./server
        run: go mod download

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...
          working-directory: ./server

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          working-directory: ./server
